language: ruby
rvm:
- 2.6.3
postgres:
  adapter: postgresql
  database: budgeting_test
  username: budgeting
before_script:
- createuser budgeting
- createdb -O budgeting budgeting_test
- gem update --system
- gem install bundler
- "bundle exec rake db:migrate"
env:
  secure: Jty8DAjv58ZoZj85500a3kOCUtUe3rDXOyadLAqxyEo8kYBbgy8a0CbHXkct3sTx5cGzrNSfauBljn0rDtybs04h0tuOd2AtC4Ijp23wwp+I5uzCaDYvW1ZGShJ/k9AHNgJXxAm4XpbxnEA09bzoMZh7GzoMOsrSArBfULHWZS/IW6Ovts6Kf2bciLLKJLI9PG4iUqI+41i8FrDQS0zBWJaYkXrceBbLsARhlFxrV7ljytzEc8oaUNegwdH75tEmFjKoKagGHy0Eq4EGEaVPkqUhxeKZHfRz399Ju2Rf1R1TItn3vehpeUWdD9ys3wAUyScQcscRexO5+AGh9/QFw5gKIIKII78pdid7tVDlrqN6wgmqidhaS45gmlnonYUFTSYWCn4INTbOtOQBGpichkkK3ZiE81M7/wn1GmWMp3ny99ZwpdLYqYMOBQ805nW/spBMQ8jxGnI091Ye3cI4Ibo1QW7G9H11K43QbPQ5p0OVDR0/6LubPUMh8rknti96G/Prv+9X4OzfVf9qOupdK1n+lvMbDklnVa/07EFTWAafVI8vqdEX6ki9k4Y2YG29unr+iO3qGf4YTBNvpARKTeDQHP4pvb5NbL0uhMcbURmuQigs+bttyImqUJsbCnUO3vKfs37pLRC9rmQvy6GrUkcDlv0hwY3j/GaXsGrHARM=
