language: ruby
rvm:
- 2.5.3
postgres:
  adapter: postgresql
  database: budgeting_test
  username: budgeting
before_script:
- createuser budgeting
- createdb -O budgeting budgeting_test
- gem update --system
- gem install bundler
- "bundle exec rake db:migrate"
